---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nongzc.
--- DateTime: 2026/1/20 21:02
---
-- 优惠卷ID
local voucherId = ARGV[1]
-- 用户ID
local userId = ARGV[2]
-- 订单id
local orderId = ARGV[3]
-- 库存Key
local stockKey = 'seckill:stock:' .. voucherId
-- 订单Key
local orderKey = 'seckill:order:' .. voucherId

-- 脚本业务
-- 判断库存是否充足 get stockKey
local stockVal = redis.call('get', stockKey)
if (tonumber(stockVal) <= 0) then
    -- 库存不足,返回1
    return 1
end

-- 判断用户是否下单 sismember orderKey userId
if (redis.call('sismember', orderKey, userId) == 1) then
    -- 存在, 说明是重复下单,返回2
    return 2
end

-- 扣库存 incrby stockKey -1
redis.call('incrby', stockKey, -1)
-- 下单 sadd orderKey userId
redis.call('sadd', orderKey, userId)

-- 发送消息到队列中 XADD stream.order * k1 v1 k2 v2 ...
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
-- 成功,返回0
return 0
